# Generated by Django 4.1.6 on 2023-02-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=11),
            preserve_default=False,
        ),
    ]
